#!/bin/bash

echo "set term png enhanced
set out 'ped2.png'
set multiplot
 set size square
 set size 0.7,1
 set size ratio -1
set ylabel 'y[m]'
set xlabel 'x[m]'
set yrange [-7:5]
set xrange [-1:12]
plot 'P0' u 6:7 w l t 'p_{r,0}=0 kg*m/s', 'P2' u 6:7 w l t 'p_{r,0}=2 kg*m/s', 'P3.5' u 6:7 w l t 'p_{r,0}=3,5 kg*m/s', 'P5' u 6:7 w l t 'p_{r,0}=5 kg*m/s'" > P_plot.p

# draw

gnuplot P_plot.p

display ped2.png
